### ISSUE TITLE
Step 8: Error in transitions

### ISSUE THREAD

**Issue by KayDee** [PolymerLabs/polymer-2-carousel#24]
Hi, I tried following the codelab with polymer 3. However only the *previous* transitions and the transition from 3rd to 4th pic (4 pics in total) is visible. Can you help ?

**Comment by keanulee** [comment]
This codelab hasn't been migrated to Polymer 3 yet, but I did try to migrate just the final step to Polymer 3 and it works (https://stackblitz.com/edit/polymer-element-example-4n6eao). Can you compare your work to this sample?

**Comment by KayDee** [comment]
I compared your file and mine till Step 8 (haven't written Step 9 yet), but i couldn't find anything.
So, could you please take a look at the code ? I published it [here](https://github.com/kayd33/polymer-carousel/tree/master). Also, i have a few variable names changed, so please bear with that.
The files are 
> [polymer-carousel.js](https://github.com/kayd33/polymer-carousel/blob/master/polymer-carousel.js)
> [mixin-carousel.js](https://github.com/kayd33/polymer-carousel/blob/master/mixin-carousel.js)
> [demo/index.html](https://github.com/kayd33/polymer-carousel/blob/master/demo/index.html)

**Comment by keanulee** [comment]
I see that you're transitioning `all` properties instead of just `transform` (https://github.com/kayd33/polymer-carousel/blob/master/polymer-carousel.js#L116) and using `translateX` instead of `translate3d` (https://github.com/kayd33/polymer-carousel/blob/master/polymer-carousel.js#L117). You also swapped the last two lines in `next()` (https://github.com/kayd33/polymer-carousel/blob/master/polymer-carousel.js#L83), but I don't think that makes a differnece.

**Comment by KayDee** [comment]
Initially i had all the things you said as the codelab. I really don't know why i changed them.
I still am lost as to what the error might be.

**Comment by KayDee** [comment]
> You also swapped the last two lines in next(), but I don't think that makes a differnece.

Well, I swapped the back and it worked.
If you have time please do explain why it worked just by swapping those lines. I really want to know.

**Comment by keanulee** [comment]
I didn't really want to explain this in the codelab because it's kind of nuanced, but reading `this.offsetWidth` actually triggers a layout:

```js
      next() {
        const elem = this.selected && this.selected.nextElementSibling;
        if (elem && !this._touchDir) {
          // Setup transition start state
          const oldSelected = this.selected;
          this._translateX(oldSelected, 0);

          /* -- Layout is triggered before _translateX() -- */
          this._translateX(elem, this.offsetWidth);

          // Start the transition
          this.selected = elem;

          /* -- Another layout is triggered before _translateX() -- */
          this._translateX(oldSelected, -this.offsetWidth, true /* transition */);_translateX()

          this._translateX(elem, 0, true /* transition */);
        }
      }
```

Setting `this.selected = elem` will change the child element that has the `selected` attribute, but this isn't reflected until layout is triggered. The transition only works after this layout. This is why I can't store the value of `this.offsetWidth` and use it in both places, even though it may look like an instance of [layout thrashing](https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing#avoid_layout_thrashing).

**Comment by KayDee** [comment]
Took a while but i understood. Thank you. Couple of follow up questions though: 
1. Why did it work on the last transition of next() ?
2. Does this layout triggering knowledge come with experience or is there specific topic to understand ?

**Comment by keanulee** [comment]
1. Unsure, haven't researched.
2. Both experience and reading articles like I mentioned above (https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing#avoid_layout_thrashing)
